<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>62261ad4-8300-4230-a99d-7b50c2f23c97</testSuiteGuid>
   <testCaseLink>
      <guid>3ea916bf-9f7b-48c4-81cf-299e37eba73a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/LoginTC/AAALoginCheck</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bda2b10c-1409-4379-8e06-e1bc2a834d73</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-2</value>
         </iterationEntity>
         <testDataId>Data Files/Sanity/ProfileCreation</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>bda2b10c-1409-4379-8e06-e1bc2a834d73</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>8fbe6c88-a39e-4d45-bc71-bdb9ca99213b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0294c9a1-2361-4921-9ae8-bb38fb903786</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a6bea80-e4ed-4a1a-988f-6b0c479c3991</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b378c6e-b09e-4c15-a166-bb47810302d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2aa738e8-7135-4383-9618-49686ef19edf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88fbc9a4-7452-44a4-bffc-f5dd07a564d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bda2b10c-1409-4379-8e06-e1bc2a834d73</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>proName</value>
         <variableId>6d025f8a-1897-47f6-9732-aa948a7feb32</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f01102ee-ec5d-4fee-a25e-1a5fdec8cd51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/PreReq/Pre-Req-Script-For-JobMonitoring-AllJobs</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4f1d6a7-dcfa-440e-a86e-3bb10a8dea6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>996e8ea2-cec6-4c30-b0d1-7cd8c8b66f02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58ab5183-dd64-4c89-9a2a-3ed385f18550</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3635dc1-452f-48c6-af58-4f9702f180b3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e32d5445-6f42-4d0f-a8ea-4b765f7310eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f0aeaa5-6880-49cb-8d7a-14ac8e0f1c1e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4143f706-55f3-4834-bd05-e0c409009b85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/PreReq/Pre-Req-Script-For-JobMonitoring-Ops</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07e6f513-a04f-4fe3-b70a-198f3f69be18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64007784-bca4-488a-8a51-9d250067468a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c87bd78-81b1-402b-ae17-375332c5d79c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e1d0a01-35b1-4e4d-b5c8-bb176ad9c1bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f94f9b9-3a18-4eca-b080-5ff2e6edd9b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1c12b7f-deff-4bfd-b652-c2cc17ec0237</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>82ced03f-7aaa-42ba-bdd7-98affd114250</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FilesModule/FileOperations</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d7255ee-2b97-45de-860a-6d4dff97674d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9db2c348-847f-41f0-800b-d8b322772339</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b950ced-8cb3-43ce-a472-81090d4db7f5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
