<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AppName</name>
   <tag></tag>
   <elementGuidId>89ef64a7-16a5-4756-9091-8f0330da6f93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='app_name_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#app_name_input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'app_name_input' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b0394e1-76f5-4cd5-ad19-d512f2ce0d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-name-input</value>
      <webElementGuid>871b7007-844a-4c5f-963c-c5cde0e46915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>app_name_input</value>
      <webElementGuid>9c84c1e3-6b26-4c84-9110-b763c6f910cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a9ebc87d-cd1d-4cd7-8cea-c4062c66a054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appName</value>
      <webElementGuid>c98b57df-c05e-4e94-b5a5-78b781f3719c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Untitled</value>
      <webElementGuid>ad92a9fb-8a5a-40fe-bd67-ba628f1bdbcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app_name_input&quot;)</value>
      <webElementGuid>06c67876-69e5-4832-a999-49bdf9e16299</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='app_name_input']</value>
      <webElementGuid>c4a914aa-6a5d-415d-91da-43c2a5f4a857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>2d03ff2f-1daa-448b-9476-28885aed923a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>d31f54fa-9fae-436d-bf9f-f46c685a9236</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
